### ISSUE TITLE
not found multiworld version 0.1.0

### ISSUE THREAD

**Issue by joaopaulq** [ksluck/Coadaptation#1]
I'm getting this error [ERROR: Could not find a version that satisfies the requirement multiworld==0.1.0] when I run `pip3 install -r requirements.txt`.

**Comment by ksluck** [comment]
Hi joão,

thanks for opening the issue! I have actually been working on the code to fix some issues and make it usable with the newest version of rlkit. If you give me a couple days I will push the update to this repository for you! Would that work for you?
-Kevin

**Comment by joaopaulq** [comment]
absolutely, thanks for the reply. be safe!

**Comment by ksluck** [comment]
I just pushed the newest version - the code is now using the newest version of rlkit so you can 'pip install -e .' rlkit following their instructions, also updated the requirements file. This should resolve the issue with multiworld.

Let me know if you run into any issues!

**Comment by ksluck** [comment]
Heya,

just an important update: The guys over at rlkit did a major commit which is not backwards compatible, so I would expect you are going to run into issues when you pull the newest version of rlkit.
There is not tag available as of right now, so I would recommend to use the version of rlkit repository at the following commit:
https://github.com/vitchyr/rlkit/commit/55ace41fb1e7b4181c15b3255247566fb49a6736
