### ISSUE TITLE
Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by chenci107** [ksluck/Coadaptation#3]
When I run "python3 main.py sac_pso_batch", I modify" render=True", a window will flash on the screen and an error will be reported"Segmentation fault(core dumped)"

**Comment by ksluck** [comment]
Hi @chenci107 
Sorry, I just saw your issue - how are you running the program exactly? Can you post the exact error message here?

My initial guess is that it could be an issue on the PyBullet-side. In the past I have seen cases where if either OpenGL is not installed, or there is something preventing PyBullet opening the GUI screen it will throw an arbitrary segmentation fault.
Can you also post some specs about your system?

**Comment by ksluck** [comment]
Closed due to inactivity
